FROM golang:1.21-alpine AS builder
WORKDIR /app

COPY go.mod ./
RUN go mod download 

COPY . .

RUN go build -o app .

#2

FROM scratch
WORKDIR /myapp
COPY --from=builder /app/app /myapp/app 

COPY store.json .

EXPOSE 8080
ENTRYPOINT ["/myapp/app"]
