version: '3.9'

services:
  web:
    build: 
      context: .  
    volumes: 
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    container_name: django_nginx
    volumes: 
       - static_volume:/staticfiles
    ports: 
       - "80:80"
    depends_on:
        - web


volumes:
   static_volume: