version: "3.9"

services: 
  db:
    image: postgres:15
    env_file: .env
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  backend:
     build:
       context: ./backend
     env_file: .env
     volumes:
        - backend_data:/app
     depends_on: 
       - db
     ports: 
         - "8000:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
        - frontend_data:/app
    depends_on:
        - backend
    ports:
        - "3000:80"

volumes:
  postgres_data:
  backend_data:
  frontend_data: